const SET_SECURITY_MOD = 'SET_SECURITY_MOD';

const FETCH_CAMERAS_REQUEST = 'FETCH_CAMERAS_REQUEST';
const FETCH_CAMERAS_SUCCESS = 'FETCH_CAMERAS_SUCCESS';
const FETCH_CAMERAS_FAILURE = 'FETCH_CAMERAS_FAILURE';

const CREATE_CAMERA_REQUEST = 'CREATE_CAMERA_REQUEST';
const CREATE_CAMERA_SUCCESS = 'CREATE_CAMERA_SUCCESS';
const CREATE_CAMERA_FAILURE = 'CREATE_CAMERA_FAILURE';

export default {
  SET_SECURITY_MOD,
  FETCH_CAMERAS_REQUEST,
  FETCH_CAMERAS_SUCCESS,
  FETCH_CAMERAS_FAILURE,
  CREATE_CAMERA_REQUEST,
  CREATE_CAMERA_SUCCESS,
  CREATE_CAMERA_FAILURE,
};
