const SET_SECURITY_MOD = 'SET_SECURITY_MOD';
const CAMERAS_REQUEST = 'CAMERAS_REQUEST';
const CAMERAS_SUCCESS = 'CAMERAS_SUCCESS';
const CAMERAS_FAILURE = 'CAMERAS_FAILURE';

export default {
  SET_SECURITY_MOD,
  CAMERAS_REQUEST,
  CAMERAS_SUCCESS,
  CAMERAS_FAILURE,
};
