const SET_SECURITY_MOD_REQUEST = 'SET_SECURITY_MOD_REQUEST';
const SET_SECURITY_MOD_SUCCESS = 'SET_SECURITY_MOD_SUCCESS';
const SET_SECURITY_MOD_FAILURE = 'SET_SECURITY_MOD_FAILURE';

const SET_SECURITY_STATUS = 'SET_SECURITY_STATUS';

const FETCH_CAMERAS_REQUEST = 'FETCH_CAMERAS_REQUEST';
const FETCH_CAMERAS_SUCCESS = 'FETCH_CAMERAS_SUCCESS';
const FETCH_CAMERAS_FAILURE = 'FETCH_CAMERAS_FAILURE';

const CREATE_CAMERA_REQUEST = 'CREATE_CAMERA_REQUEST';
const CREATE_CAMERA_SUCCESS = 'CREATE_CAMERA_SUCCESS';
const CREATE_CAMERA_FAILURE = 'CREATE_CAMERA_FAILURE';

const DELETE_CAMERA_REQUEST = 'DELETE_CAMERA_REQUEST';
const DELETE_CAMERA_SUCCESS = 'DELETE_CAMERA_SUCCESS';
const DELETE_CAMERA_FAILURE = 'DELETE_CAMERA_FAILURE';

const TOGGLE_DETECTION_CAMERA_REQUEST = 'TOGGLE_DETECTION_CAMERA_REQUEST';
const TOGGLE_DETECTION_CAMERA_SUCCESS = 'TOGGLE_DETECTION_CAMERA_SUCCESS';
const TOGGLE_DETECTION_CAMERA_FAILURE = 'TOGGLE_DETECTION_CAMERA_FAILURE';

const FETCH_ALERTS_REQUEST = 'FETCH_ALERTS_REQUEST';
const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS';
const FETCH_ALERTS_FAILURE = 'FETCH_ALERTS_FAILURE';

export default {
  SET_SECURITY_STATUS,
  SET_SECURITY_MOD_REQUEST,
  SET_SECURITY_MOD_SUCCESS,
  SET_SECURITY_MOD_FAILURE,
  FETCH_CAMERAS_REQUEST,
  FETCH_CAMERAS_SUCCESS,
  FETCH_CAMERAS_FAILURE,
  CREATE_CAMERA_REQUEST,
  CREATE_CAMERA_SUCCESS,
  CREATE_CAMERA_FAILURE,
  DELETE_CAMERA_REQUEST,
  DELETE_CAMERA_SUCCESS,
  DELETE_CAMERA_FAILURE,
  TOGGLE_DETECTION_CAMERA_REQUEST,
  TOGGLE_DETECTION_CAMERA_SUCCESS,
  TOGGLE_DETECTION_CAMERA_FAILURE,
  FETCH_ALERTS_REQUEST,
  FETCH_ALERTS_SUCCESS,
  FETCH_ALERTS_FAILURE,
};
